fixed the configure script
git-svn-id: svn+ssh://svn.code.sf.net/p/webissues/code/trunk/client@2173 c8fa975d-6fd4-4e76-b3b8-1a99b2ee3549

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4,13 +4,14 @@ prefix=/usr/local
 destdir=
 config=release
 QMAKE=
+syssqlite=no
 mac=no
 universal=no
 target=10.3
 sdk=/Developer/SDKs/MacOSX10.6.sdk
 
 usage="Usage: configure [-prefix DIR] [-destdir DIR] [-qmake PATH] [-debug]
-                 [-universal] [-target VERSION] [-sdk PATH]
+                 [-system-sqlite] [-universal] [-target VERSION] [-sdk PATH]
 
 General options:
 
@@ -18,6 +19,7 @@ General options:
   -destdir DIR   Set the destination path to DIR
   -qmake PATH    Full path to the 'qmake' program (default: autodetect)
   -debug         Build with debugging symbols
+  -system-sqlite Use system SQLite library
 
 OS X options:
 
@@ -47,6 +49,10 @@ while test $# -gt 0; do
       ;;
     -debug )
       config=debug
+      shift
+      ;;
+    -system-sqlite )
+      syssqlite=yes
       shift
       ;;
     -universal )
@@ -113,17 +119,15 @@ for i in $paths; do
     major=`echo $version | cut -d . -f 1`
     minor=`echo $version | cut -d . -f 2`
     patch=`echo $version | cut -d . -f 3`
-    if test "$major" -eq 4; then
-      if test "$minor" -ge 7; then
-        QMAKE=$i
-        break
-      fi
+    if test "$major" -eq 5; then
+      QMAKE=$i
+      break
     fi
   fi
 done
 
 if test -z "$QMAKE"; then
-  echo "*** ERROR: Cannot find 'qmake' from Qt 4.7 or newer." >&2
+  echo "*** ERROR: Cannot find 'qmake' from Qt 5." >&2
   exit 1
 fi
 
@@ -135,6 +139,10 @@ echo "# this file was generated by configure" >config.pri
 echo "CONFIG += $config" >>config.pri
 echo "PREFIX = $prefix" >>config.pri
 echo "DESTINATION = $destdir" >>config.pri
+
+if test "$syssqlite" = "yes"; then
+  echo "CONFIG += system-sqlite" >>config.pri
+fi
 
 if test "$mac" = "yes"; then
   echo "mac {" >>config.pri
